name: cardboard_bot
description: A discord bot that interacts with TCGPlayer API.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.2 <4.0.0'
publish_to: none


dependencies:
  nyxx: ^5.0.3
  nyxx_interactions: ^4.6.0
  http: ^0.13.6
  json_annotation: ^4.8.1
  intl: ^0.18.1
  logging: ^1.2.0
  collection: ^1.17.2
  yaml: ^3.1.2
  googleapis: ^11.2.0
  googleapis_auth: ^1.4.1
  kiwi: ^4.1.0
  args: ^2.4.1

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.1.5
  kiwi_generator: ^4.0.2
  lints: ^2.0.0
  test: ^1.16.0
