name: cardboard_bot
description: A discord bot that interacts with TCGPlayer API.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'
publish_to: none


dependencies:
  nyxx:
    path: C:/Users/ndshr/WebstormProjects/nyxx
  nyxx_interactions:
    path: C:/Users/ndshr/WebstormProjects/nyxx_interactions
  http: ^0.13.3
  json_annotation: ^4.4.0
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.1.5
  lints: ^1.0.0
  test: ^1.16.0
