name: cardboard_bot
description: A discord bot that interacts with TCGPlayer API.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0 <3.0.0'
publish_to: none


dependencies:
  nyxx: ^4.0.0
  nyxx_interactions: ^4.3.1
  http: ^0.13.3
  json_annotation: ^4.6.0
  intl: ^0.18.1
  logging: ^1.0.2
  collection: ^1.16.0
  yaml: ^3.1.0
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.0
  kiwi: ^4.0.2
  args: ^2.3.1

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.1.5
  kiwi_generator: ^4.0.2
  lints: ^2.0.0
  test: ^1.16.0
