steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/${_MY_IMAGE_NAME}:$SHORT_SHA", ".", "-f", "${_DOCKERFILE_NAME}"]
    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_MY_IMAGE_NAME}:$SHORT_SHA"]
    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=${_KUBERNETES_RESOURCE_FILE}
      - --image=gcr.io/$PROJECT_ID/${_MY_IMAGE_NAME}:$SHORT_SHA
      - --location=${_GKE_LOCATION}
      - --cluster=${_GKE_CLUSTER}
options:
  substitutionOption: ALLOW_LOOSE