steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/$MY_IMAGE_NAME:$SHORT_SHA", "."]
    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/$MY_IMAGE_NAME:$SHORT_SHA"]
    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=$KUBERNETES_RESOURCE_FILE
      - --image=gcr.io/$PROJECT_ID/$MY_IMAGE_NAME:$SHORT_SHA
      - --location=$GKE_LOCATION
      - --cluster=$GKE_CLUSTER
options:
  substitutionOption: ALLOW_LOOSE
  substitutions:
    _MY_IMAGE_NAME: cardboardbot
    _GKE_LOCATION: us-east1-d
    _GKE_CLUSTER: cluster-east1d
    _KUBERNETES_RESOURCE_FILE: kubernetes/